### ISSUE TITLE
Environment variable or other globally accessible variable for the bot's root directory

### ISSUE THREAD

**Issue by syntaxbullet** [syntaxbullet/kimiko#11]
I've noticed we have a lot of places in our project where we use relative pathing to get the root directory of the bot.
`const pluginDir = path.join(__dirname, '..', '..', 'plugins', pluginName);`
`private static readonly BOT_ROOT_DIR = path.join(__dirname, '..');`
and so on. It would be nice to have this globally declared in some form.

**Comment by JoshuaCF** [comment]
We already have `dotenv`, I don't see why not use an environment variable. If `dotenv` supports shell expansion, we could even have something as simple as `KIMIKO_ROOT_DIR=$(pwd)`. If not, the Kimiko core can be programmed to get its own root directory and store that in the file before loading it (or even store it as an object other code can access, but that sounds like it could get messy quickly so I'm not a big fan of that).

**Comment by syntaxbullet** [comment]
In that case, we will be using an environment variable called KIMIKO_ROOT_DIR as well as KIMIKO_PLUGIN_DIR once we switch to the more modern runtime. The codebase should change only in very minimal ways.
