### ISSUE TITLE
Set up typing for a manifest file

### ISSUE THREAD

**Issue by JoshuaCF** [syntaxbullet/kimiko#7]

**Comment by syntaxbullet** [comment]
https://github.com/syntaxbullet/kimiko/blob/5088704ecbf5da5475cdeb37faacf36d1dcbd7d1/types/src/index.ts#L55C1-L64C3

The current dev branch now includes some basic types, which are used by the CLI

https://github.com/syntaxbullet/kimiko/blob/5088704ecbf5da5475cdeb37faacf36d1dcbd7d1/cli/template/kimiko.pluginrc.ts#L1C1-L5C75

lets use this issue to discuss the specific keys needed in the types.
